"""empty message

Revision ID: 12e8f5f3746a
Revises: b2c3e7a217c7
Create Date: 2024-06-17 14:00:43.747107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e8f5f3746a'
down_revision = 'b2c3e7a217c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('api_secret', sa.String(length=200), nullable=True))
        batch_op.alter_column('account',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.alter_column('account',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('api_secret')
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
