"""empty message

Revision ID: 4a7ff389edb8
Revises: 5cb5c7750b77
Create Date: 2024-05-27 21:46:48.049690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a7ff389edb8'
down_revision = '5cb5c7750b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=10), nullable=False))
        batch_op.alter_column('paramaters',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.drop_column('key_number')
        batch_op.drop_column('stage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('key_number', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.alter_column('paramaters',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
        batch_op.drop_column('path')

    # ### end Alembic commands ###
