"""empty message

Revision ID: f78974e91b7e
Revises: ded54fc3c817
Create Date: 2024-06-04 08:17:57.962364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78974e91b7e'
down_revision = 'ded54fc3c817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('bpn', sa.String(length=20), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_column('paramaters')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paramaters', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))

    op.drop_table('sounds')
    # ### end Alembic commands ###
